name: Build IcePuzzle Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import Godot project
        run: godot --headless --editor --quit-after 10

      - name: Export Web
        run: |
          mkdir -p build/web
          godot --headless --export-release "Web" build/web/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Web build
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4